FROM ubuntu:24.10
WORKDIR /opt
# python3-pip for installing python packages
RUN apt update && apt-get install -y python3-git python3-pip && rm -rf /var/lib/apt/lists/*
ARG SJP_VERSION=0.1.1
ADD --checksum=sha256:30d9424df1eddb73912b0e2ad5375fa2c876c8e30906bec91952dfb75dcf220b https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/${SJP_VERSION}.tar.gz /tmp/app.tar.gz
RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /opt && rm /tmp/app.tar.gz
# --break-system-packages flag allow to install a non-Debian-packaged Python package
RUN pip install -r requirements.txt --break-system-packages
ENTRYPOINT ["python3", "main.py"]
