FROM ubuntu:24.10
WORKDIR /opt
# python3-pip for installing python packages
RUN apt update && apt-get install -y python3-git python3-pip && rm -rf /var/lib/apt/lists/*
ARG SJP_VERSION=0.1.1
RUN git clone https://github.com/MrDave/StaticJinjaPlus.git --branch ${SJP_VERSION}
WORKDIR /opt/StaticJinjaPlus
# --break-system-packages flag allow to install a non-Debian-packaged Python package
RUN pip install -r requirements.txt --break-system-packages
ENTRYPOINT ["python3", "main.py"]
