FROM python:slim
WORKDIR /opt
RUN apt update && apt-get install -y python3-git
ARG SJP_VERSION=0.1.1
RUN git clone https://github.com/MrDave/StaticJinjaPlus.git --branch ${SJP_VERSION}
WORKDIR /opt/StaticJinjaPlus
RUN pip install -r requirements.txt --break-system-packages
ENTRYPOINT ["python3", "main.py"]
