FROM ubuntu:24.10
WORKDIR /opt
# python3-pip for installing python packages
RUN apt update && apt-get install -y python3-git python3-pip && rm -rf /var/lib/apt/lists/*
ARG SJP_VERSION=0.1.1
ADD --checksum=sha256:3555bcfd670e134e8360ad934cb5bad1bbe2a7dad24ba7cafa0a3bb8b23c6444 https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/0.1.0.tar.gz /tmp/0.1.0.tar.gz
ADD --checksum=sha256:30d9424df1eddb73912b0e2ad5375fa2c876c8e30906bec91952dfb75dcf220b https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/0.1.1.tar.gz /tmp/0.1.1.tar.gz
RUN tar xzf /tmp/${SJP_VERSION}.tar.gz --strip-components=1 -C /opt && rm /tmp/0.1.0.tar.gz /tmp/0.1.1.tar.gz
# --break-system-packages flag allow to install a non-Debian-packaged Python package
RUN pip install -r requirements.txt --break-system-packages
ENTRYPOINT ["python3", "main.py"]
